name: Github Tester
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
      - name: Set env vars
        run: |
          echo "CGO_ENABLED=0" >> $GITHUB_ENV
          echo "${HOME}/goroot/bin" >> $GITHUB_PATH
      - uses: actions/checkout@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go get
      - uses: actions/checkout@v1
        with:
          go-version: ${{ matrix.go }}
      - run: go run main.go