name: Github Tester
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        go: [ '1.14', '1.13' ]
    name: Go ${{ matrix.go }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        run: |
          echo "::set-env name=GOPATH::$(dirname $GITHUB_WORKSPACE)"
          echo "::add-path::$(dirname $GITHUB_WORKSPACE)/bin"
        shell: bash
      - uses: actions/checkout@v1
        with:
          ref: B8
          path: src/github.com/${{ github.repository }}
        run: |
          echo $(go env GOPATH)
          echo $(go env GOROOT)
          echo $PATH
      - run: go get
      - run: go run main.go